apiVersion: v1
kind: Service
metadata:
  name: ss-pipeline-lb
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    name: http
    protocol: TCP
    targetPort: http
  selector:
    app: streamset-with-pipeline