apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamset-with-pipeline
spec:
 selector:
   matchLabels:
     app: streamset-with-pipeline
 template:
   metadata:
     labels:
       app: streamset-with-pipeline
   spec:
     containers:
     - name: my-sdc
       image: srcsakthivel/sdc-pipeline
       env:
       - name: SDC_CONF_http_authentication
         value: form
       ports:
        - containerPort: 18630
          name: http